---
title: Project 4
---

* The pdf can be viewed [here](./Projects/Project4.pdf).

## 4. HDL and age-related macular degeneration

*Chin Yang Shapland<sup>1</sup>*

<sup>1</sup>MRC Integrative Epidemiology Unit, Univerity of Bristol.

### Project Summary

Age-related macular degeneration (AMD) is a painless eye-disease that eventually leads to vision loss. A
GWAS have identified several rare and common variants located in gene regions that are associated with lipid
levels (Fritsche et al. 2016). And later the reason for association was speculated and confirmed by separate
studies (Leeuwen et al. 2018, J. Colijn et al. (2018)). Multivariable MR study showed evidence of a causal
relationship between AMD and HDL cholesterol but not with LDL cholesterol and triglycerides (Burgess and
Smith 2017). Following a Bayesian model averaging approach within a multivariable MR design, out of 30
metabolites, total cholesterol in extra-large HDL particles (XL.HDL.C) had the highest inclusion posterior
probability as a risk factor for AMD (Zuber et al. 2019). With the same summary data used in (Zuber et al.
2019), we aim to find valid genetic instruments to infer causality between XL.HDL.C and AMD.